name: Deploy to Kubernetes

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t namduong0606/golang-portal:latest .

      - name: Push Docker Image
        run: docker push namduong0606/golang-portal:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure K8s
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl get nodes

      - name: Rollout deployment
        run: |
          kubectl rollout restart deployment/golang-portal
          kubectl rollout status deployment/golang-portal
